version: '3.8'
services:
  pgadmin:
    image: alexsuf/pgadmin
    container_name: pgadmin
    ports:
      - 5050:80   # localhost:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: aleksey.zadonsky@gmail.com
      PGADMIN_DEFAULT_PASSWORD: secret
      TZ: Europe/Moscow
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./FILES:/mnt/files 
volumes:
  pgadmin_data:
    external: true